### ISSUE TITLE
project 軟刪除

### ISSUE THREAD

**Issue by Liu-Yun-Syuan** [astrocamp/15th-SyncSquad#16]

**Comment by TimChaoTW** [comment]
軟刪除說明檔，由於套件只能一個一個功能套用。
因此整理下面文件提供參考
[soft_deleted.md](https://github.com/astrocamp/15th-SyncSquad/files/13712899/soft_deleted.md)

**Comment by kaochenlong** [comment]
但這個不是該套件的 readme 就有寫了嗎？

**Comment by TimChaoTW** [comment]
我們把常用的整理出來，
詳細請參考：https://github.com/rubysherpas/paranoia
